### ISSUE TITLE
De-dupe ODES responses by ID

### ISSUE THREAD

**Issue by migurski** [mapzen/metro-extracts#232]
@sleepylemur noticed that with two ODES keys, the list of ODES extracts was doubled up.

**Comment by sleepylemur** [comment]
This was from a misunderstanding about the results of the /extracts list. /extracts?api_key=odes-1234567 returns the list of extracts associated with the developer that owns the key odes-1234567.
If you loop through all of a developer's odes keys and aggregate the results you will get duplicates.
Should just grab one of a developer's odes keys and show those extracts.
