### ISSUE TITLE
Use table style from Styleguide for table under 'Your Extracts'

### ISSUE THREAD

**Issue by souperneon** [mapzen/metro-extracts#245]
https://mapzen.com/common/styleguide/design-elements.html#tables

**Comment by binx** [comment]
![screen shot 2016-08-08 at 3 07 00 pm](https://cloud.githubusercontent.com/assets/589151/17498058/d1b9b78a-5d79-11e6-874a-eb742131a90c.png)
I followed the markup on the styleguide, but got this.

Also as far as I know, tables do not include <a> support for rows.
