### ISSUE TITLE
Style logged in user same as /developer

### ISSUE THREAD

**Issue by souperneon** [mapzen/metro-extracts#255]
Metro Extracts signed in:
![screen shot 2016-08-10 at 11 01 07 am](https://cloud.githubusercontent.com/assets/6125224/17558837/f47f4886-5ee9-11e6-82e1-22f10323b71e.png)

Developer signed in:
![screen shot 2016-08-10 at 11 03 08 am](https://cloud.githubusercontent.com/assets/6125224/17558856/08af464e-5eea-11e6-8499-fe4bd876c5e8.png)

**Comment by binx** [comment]
we'll need to access the name and gh picture for each user... @migurski @sleepylemur any idea how difficult this is to add?

**Comment by migurski** [comment]
I think it will be necessary to add the name and image URL to the Current Developer API response, definitely a @sleepylemur thing.

**Comment by sleepylemur** [comment]
i'll add it now

**Comment by souperneon** [comment]
has this been pushed live?
