### ISSUE TITLE
Alternative of Mapzen custom extract

### ISSUE THREAD

**Issue by fcujorick** [mapzen/metro-extracts#318]
Hi, 

Unfortunately the Mapzen servers will stop on feb, 1. 
I'm using the extract for making cool maps and I'm looking for a altenative, 
I've checked Hot Export Tool, but the extract form is in lines, points and polygons in stead of (for example): osm_roads, osm_waterareas. 

Is there a good alternative with these exports? Or can I rewrite the lines, points and polygons to my old exports?

**Comment by nvkelso** [comment]
Hi @fcujorick, it sounds like you should file a feature request via Github with the HOT tool to add such support.

- https://github.com/hotosm/osm-export-tool/issues

**Comment by fcujorick** [comment]
Hi @nvkelso thanks, just did :-)

**Comment by nvkelso** [comment]
Closing in favor of https://github.com/hotosm/osm-export-tool/issues/281.
