### ISSUE TITLE
URL not found

### ISSUE THREAD

**Issue by giomatfois62** [mapzen/metro-extracts#319]
Hey,
I'm trying to download some extracts from the page  
[metro-extracts](https://mapzen.com/data/metro-extracts/)
but I'm getting a 404 error.  
Are you also experiencing the issue?

**Comment by alainnguyen** [comment]
same here! https://mapzen.com/data/metro-extracts/ seems down, also got a 404.
Is there any alternative URL?

Thanks!

**Comment by iandees** [comment]
Hi there! It's not pretty, but I made a list of the Metro Extracts I saved here:

https://www.nextzen.org/metro-extracts/index.html

I hope to find some time to update these extracts and am tracking that work over at https://github.com/nextzen/metro-extracts.

**Comment by drewda** [comment]
Mentioning in the readme: https://github.com/mapzen/metro-extracts/blob/master/README.md#alternatives
